default:
  image: python:3.10-slim-bullseye

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"


cache:
  paths:
    - .cache/pip

stages:
  - pre-commit
  - test
  - deploy

test-pre-commit:
  stage: pre-commit
  before_script:
    - apt update && apt install -y --no-install-recommends git
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pre-commit run --all-files


run-tests:
  stage: test
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - python -m unittest
  cache:
    paths:
      - ${PRE_COMMIT_HOME}

deploy-int-stable:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_API_INT_STABLE --api-key=$DEPLOYMENT_KEY

deploy-production:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_API_PROD --api-key=$DEPLOYMENT_KEY
  only:
    - master
