default:
  image: python:3.10-slim-bullseye

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - test
  - deploy

run-tests:
  stage: test
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python -m unittest

deploy-int-stable:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_API_INT_STABLE --api-key=$DEPLOYMENT_KEY

deploy-production:
  image: ruby:3.1.2-bullseye
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$CYOA_API_PROD --api-key=$DEPLOYMENT_KEY
  only:
    - master